import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout, Section } from "@/components/legal/LegalLayout";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy · VFarmers" },
      { name: "description", content: "How VFarmers collects, uses, and protects your personal information." },
      { property: "og:title", content: "Privacy Policy · VFarmers" },
      { property: "og:description", content: "How VFarmers collects, uses, and protects your personal information." },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      current="Privacy Policy"
      intro="This Policy explains what personal information VFarmers collects, how we use and protect it, and the choices you have."
    >
      <Section heading="1. Information we collect">
        <p>
          We collect information you provide directly — such as your display name, username, contact
          details, country, and the identity documents and selfie you submit for verification (KYC).
          We also collect activity data generated by your use of the platform, including wallet
          balances, transactions, cycles, escrow, referrals, and device/log information.
        </p>
      </Section>
      <Section heading="2. How we use your information">
        <p>
          We use your information to operate and secure the platform, process transactions, verify
          your identity, prevent fraud and money laundering, provide support, send notifications, and
          comply with legal obligations.
        </p>
      </Section>
      <Section heading="3. Identity documents">
        <p>
          KYC documents and selfies are stored privately and access-controlled. They are used solely
          for verification, compliance, and fraud-prevention purposes, are not publicly accessible,
          and are retained only as long as necessary for those purposes or as required by law.
        </p>
      </Section>
      <Section heading="4. Sharing">
        <p>
          We do not sell your personal information. We may share it with service providers who help us
          operate the platform, and with regulators or law-enforcement where legally required. Any such
          sharing is limited to what is necessary for the stated purpose.
        </p>
      </Section>
      <Section heading="5. Security">
        <p>
          We use technical and organizational measures — including encryption in transit, access
          controls, and row-level security — to protect your data. No system is perfectly secure, so we
          encourage you to protect your credentials and enable available security features.
        </p>
      </Section>
      <Section heading="6. Your rights">
        <p>
          Subject to applicable law, you may request access to, correction of, or deletion of your
          personal information, and you may object to or restrict certain processing. Some data must be
          retained to meet legal and compliance obligations.
        </p>
      </Section>
      <Section heading="7. Data retention">
        <p>
          We retain personal information for as long as your account is active and thereafter as needed
          to comply with legal, tax, accounting, and regulatory requirements.
        </p>
      </Section>
      <Section heading="8. Changes and contact">
        <p>
          We may update this Policy; the "Effective" date above reflects the latest revision. For
          privacy requests, contact the VFarmers support team via the in-app help.
        </p>
      </Section>
    </LegalLayout>
  );
}
