/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SelectDashboardRouteImport } from './routes/select-dashboard'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MerchantSignupRouteImport } from './routes/merchant-signup'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmlRouteImport } from './routes/aml'
import { Route as MerchantRouteRouteImport } from './routes/_merchant/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRecoverWithPhraseRouteImport } from './routes/auth.recover-with-phrase'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFarmRouteImport } from './routes/_authenticated/farm'
import { Route as AuthenticatedEscrowRouteImport } from './routes/_authenticated/escrow'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedAffiliateRouteImport } from './routes/_authenticated/affiliate'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedWalletIndexRouteImport } from './routes/_authenticated/wallet.index'
import { Route as AuthenticatedEscrowIndexRouteImport } from './routes/_authenticated/escrow.index'
import { Route as AuthenticatedAffiliateIndexRouteImport } from './routes/_authenticated/affiliate.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicTestCreditRouteImport } from './routes/api/public/test-credit'
import { Route as ApiEmailSendConfirmRouteImport } from './routes/api/email/send-confirm'
import { Route as MerchantMerchantWalletRouteImport } from './routes/_merchant/merchant/wallet'
import { Route as MerchantMerchantTransferRouteImport } from './routes/_merchant/merchant/transfer'
import { Route as MerchantMerchantProfileRouteImport } from './routes/_merchant/merchant/profile'
import { Route as MerchantMerchantDashboardRouteImport } from './routes/_merchant/merchant/dashboard'
import { Route as AuthenticatedWalletHistoryRouteImport } from './routes/_authenticated/wallet.history'
import { Route as AuthenticatedEscrowIdRouteImport } from './routes/_authenticated/escrow.$id'
import { Route as AuthenticatedAffiliateDownlinesRouteImport } from './routes/_authenticated/affiliate.downlines'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin/requests'
import { Route as AuthenticatedAdminPvRouteImport } from './routes/_authenticated/admin/pv'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin/premium'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin/maintenance'
import { Route as AuthenticatedAdminKycRouteImport } from './routes/_authenticated/admin/kyc'
import { Route as AuthenticatedAdminFarmersRouteImport } from './routes/_authenticated/admin/farmers'
import { Route as AuthenticatedAdminEscrowRouteImport } from './routes/_authenticated/admin/escrow'
import { Route as AuthenticatedAdminCyclesRouteImport } from './routes/_authenticated/admin/cycles'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin/affiliates'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectDashboardRoute = SelectDashboardRouteImport.update({
  id: '/select-dashboard',
  path: '/select-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSignupRoute = MerchantSignupRouteImport.update({
  id: '/merchant-signup',
  path: '/merchant-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmlRoute = AmlRouteImport.update({
  id: '/aml',
  path: '/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRouteRoute = MerchantRouteRouteImport.update({
  id: '/_merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRecoverWithPhraseRoute = AuthRecoverWithPhraseRouteImport.update({
  id: '/recover-with-phrase',
  path: '/recover-with-phrase',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmRoute = AuthenticatedFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscrowRoute = AuthenticatedEscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliateRoute = AuthenticatedAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletIndexRoute =
  AuthenticatedWalletIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedEscrowIndexRoute =
  AuthenticatedEscrowIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEscrowRoute,
  } as any)
const AuthenticatedAffiliateIndexRoute =
  AuthenticatedAffiliateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicTestCreditRoute = ApiPublicTestCreditRouteImport.update({
  id: '/api/public/test-credit',
  path: '/api/public/test-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendConfirmRoute = ApiEmailSendConfirmRouteImport.update({
  id: '/api/email/send-confirm',
  path: '/api/email/send-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantMerchantWalletRoute = MerchantMerchantWalletRouteImport.update({
  id: '/merchant/wallet',
  path: '/merchant/wallet',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantMerchantTransferRoute =
  MerchantMerchantTransferRouteImport.update({
    id: '/merchant/transfer',
    path: '/merchant/transfer',
    getParentRoute: () => MerchantRouteRoute,
  } as any)
const MerchantMerchantProfileRoute = MerchantMerchantProfileRouteImport.update({
  id: '/merchant/profile',
  path: '/merchant/profile',
  getParentRoute: () => MerchantRouteRoute,
} as any)
const MerchantMerchantDashboardRoute =
  MerchantMerchantDashboardRouteImport.update({
    id: '/merchant/dashboard',
    path: '/merchant/dashboard',
    getParentRoute: () => MerchantRouteRoute,
  } as any)
const AuthenticatedWalletHistoryRoute =
  AuthenticatedWalletHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedEscrowIdRoute = AuthenticatedEscrowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEscrowRoute,
} as any)
const AuthenticatedAffiliateDownlinesRoute =
  AuthenticatedAffiliateDownlinesRouteImport.update({
    id: '/downlines',
    path: '/downlines',
    getParentRoute: () => AuthenticatedAffiliateRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPvRoute = AuthenticatedAdminPvRouteImport.update({
  id: '/pv',
  path: '/pv',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKycRoute = AuthenticatedAdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFarmersRoute =
  AuthenticatedAdminFarmersRouteImport.update({
    id: '/farmers',
    path: '/farmers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEscrowRoute =
  AuthenticatedAdminEscrowRouteImport.update({
    id: '/escrow',
    path: '/escrow',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCyclesRoute =
  AuthenticatedAdminCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/merchant': typeof MerchantRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/select-dashboard': typeof SelectDashboardRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/escrow': typeof AuthenticatedEscrowRouteWithChildren
  '/farm': typeof AuthenticatedFarmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/send': typeof AuthenticatedSendRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recover-with-phrase': typeof AuthRecoverWithPhraseRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/admin/farmers': typeof AuthenticatedAdminFarmersRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/pv': typeof AuthenticatedAdminPvRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/affiliate/downlines': typeof AuthenticatedAffiliateDownlinesRoute
  '/escrow/$id': typeof AuthenticatedEscrowIdRoute
  '/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/merchant/dashboard': typeof MerchantMerchantDashboardRoute
  '/merchant/profile': typeof MerchantMerchantProfileRoute
  '/merchant/transfer': typeof MerchantMerchantTransferRoute
  '/merchant/wallet': typeof MerchantMerchantWalletRoute
  '/api/email/send-confirm': typeof ApiEmailSendConfirmRoute
  '/api/public/test-credit': typeof ApiPublicTestCreditRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/escrow/': typeof AuthenticatedEscrowIndexRoute
  '/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/merchant': typeof MerchantRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/select-dashboard': typeof SelectDashboardRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/farm': typeof AuthenticatedFarmRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/send': typeof AuthenticatedSendRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recover-with-phrase': typeof AuthRecoverWithPhraseRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/admin/farmers': typeof AuthenticatedAdminFarmersRoute
  '/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/pv': typeof AuthenticatedAdminPvRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/affiliate/downlines': typeof AuthenticatedAffiliateDownlinesRoute
  '/escrow/$id': typeof AuthenticatedEscrowIdRoute
  '/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/merchant/dashboard': typeof MerchantMerchantDashboardRoute
  '/merchant/profile': typeof MerchantMerchantProfileRoute
  '/merchant/transfer': typeof MerchantMerchantTransferRoute
  '/merchant/wallet': typeof MerchantMerchantWalletRoute
  '/api/email/send-confirm': typeof ApiEmailSendConfirmRoute
  '/api/public/test-credit': typeof ApiPublicTestCreditRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/affiliate': typeof AuthenticatedAffiliateIndexRoute
  '/escrow': typeof AuthenticatedEscrowIndexRoute
  '/wallet': typeof AuthenticatedWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_merchant': typeof MerchantRouteRouteWithChildren
  '/aml': typeof AmlRoute
  '/auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/merchant': typeof MerchantRoute
  '/merchant-signup': typeof MerchantSignupRoute
  '/privacy': typeof PrivacyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/select-dashboard': typeof SelectDashboardRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/affiliate': typeof AuthenticatedAffiliateRouteWithChildren
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/escrow': typeof AuthenticatedEscrowRouteWithChildren
  '/_authenticated/farm': typeof AuthenticatedFarmRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/recover-with-phrase': typeof AuthRecoverWithPhraseRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/cycles': typeof AuthenticatedAdminCyclesRoute
  '/_authenticated/admin/escrow': typeof AuthenticatedAdminEscrowRoute
  '/_authenticated/admin/farmers': typeof AuthenticatedAdminFarmersRoute
  '/_authenticated/admin/kyc': typeof AuthenticatedAdminKycRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/admin/pv': typeof AuthenticatedAdminPvRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/affiliate/downlines': typeof AuthenticatedAffiliateDownlinesRoute
  '/_authenticated/escrow/$id': typeof AuthenticatedEscrowIdRoute
  '/_authenticated/wallet/history': typeof AuthenticatedWalletHistoryRoute
  '/_merchant/merchant/dashboard': typeof MerchantMerchantDashboardRoute
  '/_merchant/merchant/profile': typeof MerchantMerchantProfileRoute
  '/_merchant/merchant/transfer': typeof MerchantMerchantTransferRoute
  '/_merchant/merchant/wallet': typeof MerchantMerchantWalletRoute
  '/api/email/send-confirm': typeof ApiEmailSendConfirmRoute
  '/api/public/test-credit': typeof ApiPublicTestCreditRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/affiliate/': typeof AuthenticatedAffiliateIndexRoute
  '/_authenticated/escrow/': typeof AuthenticatedEscrowIndexRoute
  '/_authenticated/wallet/': typeof AuthenticatedWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aml'
    | '/auth'
    | '/forgot-password'
    | '/merchant'
    | '/merchant-signup'
    | '/privacy'
    | '/risk-disclosure'
    | '/select-dashboard'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/admin'
    | '/achievements'
    | '/affiliate'
    | '/coupons'
    | '/dashboard'
    | '/deposit'
    | '/escrow'
    | '/farm'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/send'
    | '/upgrade'
    | '/verify'
    | '/wallet'
    | '/withdraw'
    | '/auth/callback'
    | '/auth/recover-with-phrase'
    | '/auth/reset-password'
    | '/admin/affiliates'
    | '/admin/audit'
    | '/admin/coupons'
    | '/admin/cycles'
    | '/admin/escrow'
    | '/admin/farmers'
    | '/admin/kyc'
    | '/admin/maintenance'
    | '/admin/premium'
    | '/admin/pv'
    | '/admin/requests'
    | '/admin/settings'
    | '/affiliate/downlines'
    | '/escrow/$id'
    | '/wallet/history'
    | '/merchant/dashboard'
    | '/merchant/profile'
    | '/merchant/transfer'
    | '/merchant/wallet'
    | '/api/email/send-confirm'
    | '/api/public/test-credit'
    | '/admin/'
    | '/affiliate/'
    | '/escrow/'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aml'
    | '/auth'
    | '/forgot-password'
    | '/merchant'
    | '/merchant-signup'
    | '/privacy'
    | '/risk-disclosure'
    | '/select-dashboard'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/achievements'
    | '/coupons'
    | '/dashboard'
    | '/deposit'
    | '/farm'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/send'
    | '/upgrade'
    | '/verify'
    | '/withdraw'
    | '/auth/callback'
    | '/auth/recover-with-phrase'
    | '/auth/reset-password'
    | '/admin/affiliates'
    | '/admin/audit'
    | '/admin/coupons'
    | '/admin/cycles'
    | '/admin/escrow'
    | '/admin/farmers'
    | '/admin/kyc'
    | '/admin/maintenance'
    | '/admin/premium'
    | '/admin/pv'
    | '/admin/requests'
    | '/admin/settings'
    | '/affiliate/downlines'
    | '/escrow/$id'
    | '/wallet/history'
    | '/merchant/dashboard'
    | '/merchant/profile'
    | '/merchant/transfer'
    | '/merchant/wallet'
    | '/api/email/send-confirm'
    | '/api/public/test-credit'
    | '/admin'
    | '/affiliate'
    | '/escrow'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_merchant'
    | '/aml'
    | '/auth'
    | '/forgot-password'
    | '/merchant'
    | '/merchant-signup'
    | '/privacy'
    | '/risk-disclosure'
    | '/select-dashboard'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/_authenticated/admin'
    | '/_authenticated/achievements'
    | '/_authenticated/affiliate'
    | '/_authenticated/coupons'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/escrow'
    | '/_authenticated/farm'
    | '/_authenticated/history'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/send'
    | '/_authenticated/upgrade'
    | '/_authenticated/verify'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/auth/callback'
    | '/auth/recover-with-phrase'
    | '/auth/reset-password'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/cycles'
    | '/_authenticated/admin/escrow'
    | '/_authenticated/admin/farmers'
    | '/_authenticated/admin/kyc'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/premium'
    | '/_authenticated/admin/pv'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/settings'
    | '/_authenticated/affiliate/downlines'
    | '/_authenticated/escrow/$id'
    | '/_authenticated/wallet/history'
    | '/_merchant/merchant/dashboard'
    | '/_merchant/merchant/profile'
    | '/_merchant/merchant/transfer'
    | '/_merchant/merchant/wallet'
    | '/api/email/send-confirm'
    | '/api/public/test-credit'
    | '/_authenticated/admin/'
    | '/_authenticated/affiliate/'
    | '/_authenticated/escrow/'
    | '/_authenticated/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MerchantRouteRoute: typeof MerchantRouteRouteWithChildren
  AmlRoute: typeof AmlRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MerchantRoute: typeof MerchantRoute
  MerchantSignupRoute: typeof MerchantSignupRoute
  PrivacyRoute: typeof PrivacyRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  SelectDashboardRoute: typeof SelectDashboardRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiEmailSendConfirmRoute: typeof ApiEmailSendConfirmRoute
  ApiPublicTestCreditRoute: typeof ApiPublicTestCreditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-dashboard': {
      id: '/select-dashboard'
      path: '/select-dashboard'
      fullPath: '/select-dashboard'
      preLoaderRoute: typeof SelectDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-signup': {
      id: '/merchant-signup'
      path: '/merchant-signup'
      fullPath: '/merchant-signup'
      preLoaderRoute: typeof MerchantSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aml': {
      id: '/aml'
      path: '/aml'
      fullPath: '/aml'
      preLoaderRoute: typeof AmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_merchant': {
      id: '/_merchant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MerchantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/recover-with-phrase': {
      id: '/auth/recover-with-phrase'
      path: '/recover-with-phrase'
      fullPath: '/auth/recover-with-phrase'
      preLoaderRoute: typeof AuthRecoverWithPhraseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify': {
      id: '/_authenticated/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AuthenticatedVerifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farm': {
      id: '/_authenticated/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof AuthenticatedFarmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escrow': {
      id: '/_authenticated/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof AuthenticatedEscrowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliate': {
      id: '/_authenticated/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AuthenticatedAffiliateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet/': {
      id: '/_authenticated/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof AuthenticatedWalletIndexRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/escrow/': {
      id: '/_authenticated/escrow/'
      path: '/'
      fullPath: '/escrow/'
      preLoaderRoute: typeof AuthenticatedEscrowIndexRouteImport
      parentRoute: typeof AuthenticatedEscrowRoute
    }
    '/_authenticated/affiliate/': {
      id: '/_authenticated/affiliate/'
      path: '/'
      fullPath: '/affiliate/'
      preLoaderRoute: typeof AuthenticatedAffiliateIndexRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/test-credit': {
      id: '/api/public/test-credit'
      path: '/api/public/test-credit'
      fullPath: '/api/public/test-credit'
      preLoaderRoute: typeof ApiPublicTestCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send-confirm': {
      id: '/api/email/send-confirm'
      path: '/api/email/send-confirm'
      fullPath: '/api/email/send-confirm'
      preLoaderRoute: typeof ApiEmailSendConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_merchant/merchant/wallet': {
      id: '/_merchant/merchant/wallet'
      path: '/merchant/wallet'
      fullPath: '/merchant/wallet'
      preLoaderRoute: typeof MerchantMerchantWalletRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/_merchant/merchant/transfer': {
      id: '/_merchant/merchant/transfer'
      path: '/merchant/transfer'
      fullPath: '/merchant/transfer'
      preLoaderRoute: typeof MerchantMerchantTransferRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/_merchant/merchant/profile': {
      id: '/_merchant/merchant/profile'
      path: '/merchant/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantMerchantProfileRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/_merchant/merchant/dashboard': {
      id: '/_merchant/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantMerchantDashboardRouteImport
      parentRoute: typeof MerchantRouteRoute
    }
    '/_authenticated/wallet/history': {
      id: '/_authenticated/wallet/history'
      path: '/history'
      fullPath: '/wallet/history'
      preLoaderRoute: typeof AuthenticatedWalletHistoryRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/escrow/$id': {
      id: '/_authenticated/escrow/$id'
      path: '/$id'
      fullPath: '/escrow/$id'
      preLoaderRoute: typeof AuthenticatedEscrowIdRouteImport
      parentRoute: typeof AuthenticatedEscrowRoute
    }
    '/_authenticated/affiliate/downlines': {
      id: '/_authenticated/affiliate/downlines'
      path: '/downlines'
      fullPath: '/affiliate/downlines'
      preLoaderRoute: typeof AuthenticatedAffiliateDownlinesRouteImport
      parentRoute: typeof AuthenticatedAffiliateRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pv': {
      id: '/_authenticated/admin/pv'
      path: '/pv'
      fullPath: '/admin/pv'
      preLoaderRoute: typeof AuthenticatedAdminPvRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/premium': {
      id: '/_authenticated/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kyc': {
      id: '/_authenticated/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AuthenticatedAdminKycRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/farmers': {
      id: '/_authenticated/admin/farmers'
      path: '/farmers'
      fullPath: '/admin/farmers'
      preLoaderRoute: typeof AuthenticatedAdminFarmersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/escrow': {
      id: '/_authenticated/admin/escrow'
      path: '/escrow'
      fullPath: '/admin/escrow'
      preLoaderRoute: typeof AuthenticatedAdminEscrowRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cycles': {
      id: '/_authenticated/admin/cycles'
      path: '/cycles'
      fullPath: '/admin/cycles'
      preLoaderRoute: typeof AuthenticatedAdminCyclesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCyclesRoute: typeof AuthenticatedAdminCyclesRoute
  AuthenticatedAdminEscrowRoute: typeof AuthenticatedAdminEscrowRoute
  AuthenticatedAdminFarmersRoute: typeof AuthenticatedAdminFarmersRoute
  AuthenticatedAdminKycRoute: typeof AuthenticatedAdminKycRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedAdminPvRoute: typeof AuthenticatedAdminPvRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminCyclesRoute: AuthenticatedAdminCyclesRoute,
    AuthenticatedAdminEscrowRoute: AuthenticatedAdminEscrowRoute,
    AuthenticatedAdminFarmersRoute: AuthenticatedAdminFarmersRoute,
    AuthenticatedAdminKycRoute: AuthenticatedAdminKycRoute,
    AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
    AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
    AuthenticatedAdminPvRoute: AuthenticatedAdminPvRoute,
    AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAffiliateRouteChildren {
  AuthenticatedAffiliateDownlinesRoute: typeof AuthenticatedAffiliateDownlinesRoute
  AuthenticatedAffiliateIndexRoute: typeof AuthenticatedAffiliateIndexRoute
}

const AuthenticatedAffiliateRouteChildren: AuthenticatedAffiliateRouteChildren =
  {
    AuthenticatedAffiliateDownlinesRoute: AuthenticatedAffiliateDownlinesRoute,
    AuthenticatedAffiliateIndexRoute: AuthenticatedAffiliateIndexRoute,
  }

const AuthenticatedAffiliateRouteWithChildren =
  AuthenticatedAffiliateRoute._addFileChildren(
    AuthenticatedAffiliateRouteChildren,
  )

interface AuthenticatedEscrowRouteChildren {
  AuthenticatedEscrowIdRoute: typeof AuthenticatedEscrowIdRoute
  AuthenticatedEscrowIndexRoute: typeof AuthenticatedEscrowIndexRoute
}

const AuthenticatedEscrowRouteChildren: AuthenticatedEscrowRouteChildren = {
  AuthenticatedEscrowIdRoute: AuthenticatedEscrowIdRoute,
  AuthenticatedEscrowIndexRoute: AuthenticatedEscrowIndexRoute,
}

const AuthenticatedEscrowRouteWithChildren =
  AuthenticatedEscrowRoute._addFileChildren(AuthenticatedEscrowRouteChildren)

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletHistoryRoute: typeof AuthenticatedWalletHistoryRoute
  AuthenticatedWalletIndexRoute: typeof AuthenticatedWalletIndexRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletHistoryRoute: AuthenticatedWalletHistoryRoute,
  AuthenticatedWalletIndexRoute: AuthenticatedWalletIndexRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAffiliateRoute: typeof AuthenticatedAffiliateRouteWithChildren
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedEscrowRoute: typeof AuthenticatedEscrowRouteWithChildren
  AuthenticatedFarmRoute: typeof AuthenticatedFarmRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAffiliateRoute: AuthenticatedAffiliateRouteWithChildren,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedEscrowRoute: AuthenticatedEscrowRouteWithChildren,
  AuthenticatedFarmRoute: AuthenticatedFarmRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedVerifyRoute: AuthenticatedVerifyRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MerchantRouteRouteChildren {
  MerchantMerchantDashboardRoute: typeof MerchantMerchantDashboardRoute
  MerchantMerchantProfileRoute: typeof MerchantMerchantProfileRoute
  MerchantMerchantTransferRoute: typeof MerchantMerchantTransferRoute
  MerchantMerchantWalletRoute: typeof MerchantMerchantWalletRoute
}

const MerchantRouteRouteChildren: MerchantRouteRouteChildren = {
  MerchantMerchantDashboardRoute: MerchantMerchantDashboardRoute,
  MerchantMerchantProfileRoute: MerchantMerchantProfileRoute,
  MerchantMerchantTransferRoute: MerchantMerchantTransferRoute,
  MerchantMerchantWalletRoute: MerchantMerchantWalletRoute,
}

const MerchantRouteRouteWithChildren = MerchantRouteRoute._addFileChildren(
  MerchantRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthRecoverWithPhraseRoute: typeof AuthRecoverWithPhraseRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthRecoverWithPhraseRoute: AuthRecoverWithPhraseRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MerchantRouteRoute: MerchantRouteRouteWithChildren,
  AmlRoute: AmlRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MerchantRoute: MerchantRoute,
  MerchantSignupRoute: MerchantSignupRoute,
  PrivacyRoute: PrivacyRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  SelectDashboardRoute: SelectDashboardRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
  ApiEmailSendConfirmRoute: ApiEmailSendConfirmRoute,
  ApiPublicTestCreditRoute: ApiPublicTestCreditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
